# Generated by Django 5.1.6 on 2025-03-03 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('excited', 'Excited'), ('content', 'Content'), ('neutral', 'Neutral'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('sad', 'Sad'), ('angry', 'Angry'), ('tired', 'Tired')], max_length=20)),
                ('intensity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('activities', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
