# Generated by Django 5.1.6 on 2025-03-03 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_moodentry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('dominant_mood', models.CharField(max_length=20)),
                ('mood_distribution', models.JSONField(default=dict)),
                ('mood_timeseries', models.JSONField(default=dict)),
                ('top_activities', models.JSONField(default=dict)),
                ('activity_correlations', models.JSONField(default=dict)),
                ('intensity_stats', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Mood Insight',
                'verbose_name_plural': 'AI Mood Insights',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_entries', to='moods.aimoodinsight'),
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('activity', 'Activity Recommendation'), ('pattern', 'Pattern Recognition'), ('warning', 'Mood Warning')], max_length=50)),
                ('content', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='moods.aimoodinsight')),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'ordering': ['-generated_at'],
            },
        ),
    ]
